"""The single screen of loads and corrections, checked against the real rules.

RF-20 asks for one screen that gathers every load and correction, and RF-21
that each person is offered only theirs. Both answers live in
`frontend/lib/operations/actions.ts`: a typed registry where each action
declares the section its route already demands and whether it demands the level
to write, plus `actionsFor()`, which filters it by the permission map the
backend hands out with the session.

Why a Python test for TypeScript: the frontend has no test runner, and adding
one to hold a couple of static rules is a bigger change than they deserve — the
same reasoning as `test_auth_pages.py` and `test_dates_have_a_timezone.py`. If
a frontend suite ever exists, this belongs there.

What could not be checked from the browser side anyway is the half that matters
here. The registry names a section as a **string**, and the only thing that
says whether that string is a real part of the business is
`app.modules.identity.permissions.Section`, in Python. The TypeScript union
comes from `lib/api/types.ts`, a generated file that is checked in and
regenerated by hand, so it can lag behind the enum it was generated from — and
an invented section does not fail loudly: `canEdit` reads `undefined` from the
permission map, calls it `NONE`, and the action disappears for **everybody**,
including the owner. A screen that quietly offers nothing looks exactly like a
screen whose feature was never built.

So the questions this file asks are the ones the matrix answers:

1. every section the registry names exists;
2. purchasing and sales are offered **different** sets, and neither of them is
   empty — the case `/analyze` raised as H-1, because a registry that only
   listed the two actions 003 brings would leave whoever handles purchasing
   opening the screen to nothing;
3. the owner is offered all of them;
4. every action's `href` lands on a page that exists, because an action whose
   screen is not there is a dead card that still counts as "purchasing has
   something".

And two more about the code rather than the registry: that the screen filters
by the session instead of listing the actions itself, and that `actionsFor()`
asks `canEdit` for a writing action and `canSee` for a reading one. That last
rule is written twice — once in TypeScript and once, as `offered_to()` below,
in Python — and two copies of a rule are one rule and one bug unless something
holds them together.

None of this is the permission. The refusal lives in the route — every endpoint
declares its own authorisation and `test_route_authorization.py` says so. This
file checks that what is *offered* agrees with what would be *allowed*, which
is a different failure: an action offered to somebody the route will refuse, or
hidden from somebody the route would admit.

RF-22 closes the same screen and is the last section here: an action that
finishes has to tell whoever ran it whether it was applied or whether it
failed. That one is not about the registry but about the dialog where a
correction is actually made — and it is checked the same way, and for the same
reason, because it is the same missing test runner.
"""

import re
from dataclasses import dataclass
from pathlib import Path

import pytest

import app
from app.modules.identity.permissions import Level, Section, level_for

REPOSITORY_ROOT = Path(app.__file__).resolve().parents[2]
REGISTRY = REPOSITORY_ROOT / "frontend" / "lib" / "operations" / "actions.ts"
PRIVATE_PAGES = REPOSITORY_ROOT / "frontend" / "app" / "(private)"
SCREEN = PRIVATE_PAGES / "acciones" / "page.tsx"

# The three roles, spelled as `permissions.MATRIX` keys them. `UserRole` lives
# inside `identity` and stays there: the matrix is keyed by plain strings on
# purpose, and this file only reads it.
OWNER = "OWNER"
PURCHASING = "PURCHASING"
SALES = "SALES"

# `export const MANUAL_ACTIONS: readonly ManualAction[] = [ ... ]`, up to the
# closing bracket in the first column. `[^=]*` walks past the type annotation,
# whose own `[]` would otherwise be mistaken for the array.
MANUAL_ACTIONS = re.compile(
    r"^export const MANUAL_ACTIONS[^=]*=\s*\[(.*?)^\]", re.DOTALL | re.MULTILINE
)
# One entry, as a whole object literal. `[^{}]*` cannot leave the braces it
# opened, so a field is only ever read from the action that declares it — and
# each field is then found on its own, in any order. TypeScript does not fix
# the order of an object's properties, and a parse that assumed one would skip
# an entry written differently instead of failing: the action would vanish
# from every test in this file, H-1's guard included.
ENTRY = re.compile(r"\{(?P<body>[^{}]*)\}", re.DOTALL)
FIELDS = {
    "id": re.compile(r"\bid:\s*'(?P<value>[^']+)'"),
    "href": re.compile(r"\bhref:\s*'(?P<value>[^']+)'"),
    "section": re.compile(r"\bsection:\s*'(?P<value>[^']+)'"),
    "writes": re.compile(r"\bwrites:\s*(?P<value>true|false)"),
}
# How many entries were declared, whatever shape they were written in — the
# count `registry()` has to match.
DECLARED = re.compile(r"^\s+id:", re.MULTILINE)

# What the screen must do with the registry, and what it must not do instead.
FILTERS_BY_SESSION = re.compile(r"actionsFor\s*\(\s*session\.permissions\s*\)")
LISTS_THEM_ITSELF = re.compile(r"\bMANUAL_ACTIONS\b")
# The rule `offered_to()` reimplements below, pinned on the TypeScript side so
# the two cannot drift: a swapped `canEdit`/`canSee` would leave every test in
# `TestEachRoleIsOfferedItsOwnActions` green while the screen offered actions
# the route refuses.
THE_LEVEL_IT_DEMANDS = re.compile(
    r"action\.writes\s*\?\s*canEdit\(\s*permissions\s*,\s*action\.section\s*\)"
    r"\s*:\s*canSee\(\s*permissions\s*,\s*action\.section\s*\)"
)


@dataclass(frozen=True, slots=True)
class RegisteredAction:
    """One line of the registry, as far as authorisation is concerned."""

    id: str
    href: str
    section: str
    writes: bool


def registry_source() -> str:
    """`actions.ts`, whole."""
    return REGISTRY.read_text(encoding="utf-8")


def declared_block() -> str:
    """The body of the `MANUAL_ACTIONS` array, or nothing if its shape moved."""
    listed = MANUAL_ACTIONS.search(registry_source())
    return listed.group(1) if listed is not None else ""


def registry() -> list[RegisteredAction]:
    """Every action declared in `actions.ts` that could be read whole.

    An entry missing one of the four fields is left out rather than guessed at,
    and `test_every_entry_was_read` is what turns that silence into a failure.
    """
    actions = []
    for entry in ENTRY.finditer(declared_block()):
        found = {name: pattern.search(entry["body"]) for name, pattern in FIELDS.items()}
        if any(field is None for field in found.values()):
            continue
        actions.append(
            RegisteredAction(
                id=found["id"]["value"],
                href=found["href"]["value"],
                section=found["section"]["value"],
                writes=found["writes"]["value"] == "true",
            )
        )
    return actions


def section_of(action: RegisteredAction) -> Section:
    """The action's section as the business knows it, or say it is invented."""
    try:
        return Section(action.section)
    except ValueError:
        pytest.fail(f"«{action.id}» declares a section that does not exist: {action.section!r}")


def offered_to(role: str) -> set[str]:
    """The actions this role would be shown, by the rule the screen applies.

    `actionsFor()` asks `canEdit` for a writing action and `canSee` for a
    reading one, over the map `permissions_for(role)` builds — which is
    `level_for` on every section. So this is the same question, asked of the
    matrix the backend actually enforces rather than of a copy of it.
    """
    return {
        action.id
        for action in registry()
        if level_for(role, section_of(action)) >= (Level.WRITE if action.writes else Level.READ)
    }


@pytest.mark.unit
class TestTheRegistryNamesRealSections:
    """A section that does not exist hides its action from everybody."""

    def test_there_are_actions_to_check(self) -> None:
        """A moved file or a renamed constant must not quietly pass this file."""
        # Arrange / Act
        actions = registry()

        # Assert
        assert actions, f"no MANUAL_ACTIONS entries parsed out of {REGISTRY}"

    def test_every_entry_was_read(self) -> None:
        """An action this file could not parse must break it, not disappear.

        Every other test here counts what `registry()` returns, so an entry
        skipped is an entry nobody checks: its section is never validated, its
        page is never looked for, and the owner test compares the shortened
        list against itself and passes.
        """
        # Arrange / Act
        declared = len(DECLARED.findall(declared_block()))

        # Assert
        assert len(registry()) == declared, (
            f"{declared} actions are declared and {len(registry())} could be read: "
            "one of them is written in a shape this file does not parse, and is "
            "silently going unchecked."
        )

    def test_no_two_actions_share_an_id(self) -> None:
        """The id is the React key, and the name the rest of this file counts by."""
        # Arrange / Act
        ids = [action.id for action in registry()]

        # Assert
        assert len(ids) == len(set(ids)), f"repeated action ids in the registry: {ids}"

    @pytest.mark.parametrize("action", registry(), ids=lambda action: action.id)
    def test_its_section_exists(self, action: RegisteredAction) -> None:
        """Otherwise the permission map answers `undefined`, read as `NONE`."""
        # Arrange
        sections = {section.value for section in Section}

        # Assert
        assert action.section in sections, (
            f"«{action.id}» declares a section that does not exist: {action.section!r}. "
            "The permission map has no entry for it, `canEdit` reads it as NONE, and "
            "the action disappears for everybody, the owner included."
        )


@pytest.mark.unit
class TestEveryActionLeadsSomewhere:
    """RF-20: the single screen is a launcher, and a launcher can misfire."""

    @pytest.mark.parametrize("action", registry(), ids=lambda action: action.id)
    def test_its_page_exists(self, action: RegisteredAction) -> None:
        """The action is done on the screen its `href` points at, so it has to be there.

        A card that leads to a 404 still counts as an action offered: whoever
        handles purchasing would be told they have something to do and find
        nothing when they press it, and `test_purchasing_is_offered_something`
        would go on saying the screen is fine.
        """
        # Arrange / Act
        page = PRIVATE_PAGES / action.href.strip("/") / "page.tsx"

        # Assert
        assert page.exists(), (
            f"«{action.id}» is offered at {action.href}, and there is no page there: {page}"
        )


@pytest.mark.unit
class TestEachRoleIsOfferedItsOwnActions:
    """RF-21, resolved against the matrix rather than against a second copy."""

    def test_it_asks_for_the_level_the_action_demands(self) -> None:
        """The rule `offered_to()` reimplements, read off `actionsFor()` itself.

        The four tests below ask the matrix what each role would be offered,
        using a Python copy of the filter. Nothing else says the TypeScript
        still filters that way: swap `canEdit` for `canSee` and every one of
        them stays green while the screen offers a writing action to somebody
        who may only read it — and the route, which is the real permission,
        answers 403 when they press it.
        """
        # Arrange / Act
        source = registry_source()

        # Assert
        assert THE_LEVEL_IT_DEMANDS.search(source), (
            "`actionsFor()` no longer asks canEdit for a writing action and canSee "
            "for a reading one, so what this file checks is no longer the rule the "
            "screen applies."
        )

    def test_purchasing_is_offered_something(self) -> None:
        """The H-1 case: a registry holding only 003's actions leaves them nothing.

        Prices and the review queue are purchasing's, the product catalog and
        undoing a correction are not — so if the registry ever narrowed to what
        this feature added, Marcela would open the single screen and read that
        her access has no actions at all.
        """
        # Arrange / Act
        purchasing = offered_to(PURCHASING)

        # Assert
        assert purchasing, (
            "whoever handles purchasing opens the one screen of loads and "
            "corrections and is offered nothing: the registry lost the actions "
            "that are theirs."
        )

    def test_sales_is_offered_something(self) -> None:
        """And the same for Julián, whose section is the catalog."""
        # Arrange / Act
        sales = offered_to(SALES)

        # Assert
        assert sales, (
            "whoever handles sales opens the one screen of loads and corrections "
            "and is offered nothing."
        )

    def test_the_two_sets_are_different(self) -> None:
        """RF-21 literally: the screen shows Marcela actions Julián does not get.

        Different in both directions, which is the reading that means anything:
        one set being a subset of the other would satisfy `!=` while still
        offering the smaller role a strictly poorer version of the same screen.
        """
        # Arrange / Act
        purchasing = offered_to(PURCHASING)
        sales = offered_to(SALES)

        # Assert
        assert purchasing - sales, (
            f"purchasing is offered nothing sales is not: {sorted(purchasing)}"
        )
        assert sales - purchasing, f"sales is offered nothing purchasing is not: {sorted(sales)}"

    def test_the_owner_is_offered_all_of_them(self) -> None:
        """The owner reaches every section, so the screen hides nothing from them."""
        # Arrange
        everything = {action.id for action in registry()}

        # Act
        owner = offered_to(OWNER)

        # Assert
        assert owner == everything, (
            f"the owner is not offered {sorted(everything - owner)}, and reaches every section"
        )


@pytest.fixture(scope="module")
def screen_source() -> str:
    """The source of the single screen, read once."""
    return SCREEN.read_text(encoding="utf-8")


@pytest.mark.unit
class TestTheScreenFiltersByTheSession:
    """RF-20: one screen, and the list on it is the session's, not a fixed one."""

    def test_the_screen_exists(self) -> None:
        """RF-20 is a route before it is anything else."""
        # Assert
        assert SCREEN.exists(), f"{SCREEN} is the single screen RF-20 asks for"

    def test_it_asks_the_registry_what_this_session_may_do(self, screen_source: str) -> None:
        """`actionsFor(session.permissions)` and not a list written by hand."""
        # Assert
        assert FILTERS_BY_SESSION.search(screen_source), (
            "the actions screen does not filter the registry by the session's "
            "permissions, so it shows everybody the same list (RF-21)."
        )

    def test_it_does_not_reach_past_the_filter(self, screen_source: str) -> None:
        """Rendering `MANUAL_ACTIONS` directly would put the filter out of the way."""
        # Assert
        assert not LISTS_THEM_ITSELF.search(screen_source), (
            "the actions screen names MANUAL_ACTIONS: whatever it renders from "
            "it is unfiltered, and offers actions the route will refuse."
        )


# The one place where an action actually finishes in front of somebody, and so
# the one place RF-22 can be broken: a dialog that hides itself.
DIALOG = REPOSITORY_ROOT / "frontend" / "components" / "catalog" / "CorrectionDialog.tsx"

# `if (!open) { … return … }` — what the component renders while it is closed.
# The flag is read out of the condition instead of being spelled here, so a
# rename does not turn this rule off.
WHILE_CLOSED = re.compile(r"if\s*\(\s*!\s*(?P<flag>\w+)\s*\)\s*\{")
RETURNS = re.compile(r"\breturn\b")
# `setSomething({ ok: true, … })` — recording that the action was applied. The
# setter is captured because the state it writes is what the JSX renders, and
# the name of that state follows from it.
RECORDS_SUCCESS = re.compile(r"\b(?P<setter>set[A-Z]\w*)\(\s*\{[^{}]*\bok:\s*true\b[^{}]*\}\s*\)")
# The function that submits, written either way. Which one it is, is decided by
# what it does — it is the one that records the outcome — and not by its name.
SUBMIT_HANDLER = re.compile(
    r"async\s+function\s+\w+\s*\([^()]*\)\s*\{|const\s+\w+\s*=\s*async\s*\([^()]*\)[^{]*\{"
)


def braced_block(source: str, opening: int) -> str:
    """What lies between the brace at `opening` and the one that closes it."""
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1 : index]
    return ""


def what_runs_on_success(code: str) -> str:
    """The code with every branch that returns early taken out of it.

    What is left is what a run that reaches the end executes — the success
    path — whatever order the statements were written in. That is the whole
    point of asking it this way: the rule below is about which decisions the
    component takes together, not about which line sits under which.
    """
    kept: list[str] = []
    index = 0
    while index < len(code):
        if code[index] == "{":
            body = braced_block(code, index)
            if not RETURNS.search(body):
                kept.append("{" + what_runs_on_success(body) + "}")
            index += len(body) + 2
            continue
        kept.append(code[index])
        index += 1
    return "".join(kept)


@dataclass(frozen=True, slots=True)
class SelfHidingDialog:
    """A component that shows a form while open and a button while closed."""

    flag: str
    """The state that says the form is open."""

    while_closed: str
    """What it renders when that state is false."""

    on_submit: str
    """The body of the function that sends the correction."""

    setter: str
    """The state setter it calls to record that the action was applied."""

    @property
    def closes_itself(self) -> re.Pattern[str]:
        """`setOpen(false)`, spelled from the flag rather than assumed."""
        return re.compile(rf"\bset{self.flag[0].upper()}{self.flag[1:]}\(\s*false\s*\)")

    @property
    def outcome(self) -> str:
        """The state the outcome is written to: what the JSX has to render."""
        return self.setter[3].lower() + self.setter[4:]


def read_dialog() -> SelfHidingDialog | None:
    """`CorrectionDialog.tsx` as far as RF-22 is concerned, or nothing.

    Nothing means the component stopped being the shape this rule talks about
    — it no longer hides itself, or no longer records an outcome — and
    `test_it_hides_itself_and_reports_a_result` is what turns that into a
    failure instead of a rule that quietly stops applying.
    """
    source = DIALOG.read_text(encoding="utf-8")

    closed = next(
        (
            (found["flag"], block)
            for found in WHILE_CLOSED.finditer(source)
            if RETURNS.search(block := braced_block(source, found.end() - 1))
        ),
        None,
    )
    submitted = next(
        (
            (block, recorded["setter"])
            for found in SUBMIT_HANDLER.finditer(source)
            if (recorded := RECORDS_SUCCESS.search(block := braced_block(source, found.end() - 1)))
        ),
        None,
    )
    if closed is None or submitted is None:
        return None
    return SelfHidingDialog(
        flag=closed[0], while_closed=closed[1], on_submit=submitted[0], setter=submitted[1]
    )


@pytest.mark.unit
class TestTheResultOfACorrectionReachesTheScreen:
    """RF-22: an action that finishes tells whoever ran it how it went.

    The backend half is covered by `test_action_outcomes.py`: the refusals, and
    the correction that goes through. What no test says is that the answer
    arrives in front of the person, and that is the half worth checking here —
    an outcome the API returned and the screen never showed is, from the desk
    where the work happens, indistinguishable from nothing having happened.

    `CorrectionDialog` is where it can go wrong, because it hides itself: while
    `open` is false it renders only the button that opens it. So *saying it
    worked* and *closing* are one decision, and a component that takes both in
    the same run writes the message into a place nobody will ever look.

    Why a Python test for TSX: the same reason as the rest of this file — the
    frontend has no runner. And why it is written against the code's decisions
    rather than its lines: a static reading of a component is only worth having
    if it survives the component being rearranged. The question asked is the
    behaviour — *can the person read that it worked?* — and there is more than
    one honest answer: keep the dialog open on success, or render the outcome
    from the closed branch too. Either passes.
    """

    def test_the_dialog_is_there_to_read(self) -> None:
        """A move or a rename must not quietly turn this rule off."""
        # Assert
        assert DIALOG.exists(), f"{DIALOG} is where a correction is confirmed (RF-11, RF-22)"

    def test_it_hides_itself_and_reports_a_result(self) -> None:
        """The two facts the rule below stands on, checked before it is applied.

        If the component stops hiding itself, or stops recording an outcome,
        the next test has nothing to say and would say it in green. This one
        fails instead, and whoever reads it knows the rule has to be rewritten
        rather than deleted.
        """
        # Arrange / Act
        dialog = read_dialog()

        # Assert
        assert dialog is not None, (
            f"{DIALOG.name} no longer reads as a dialog that hides itself behind a flag "
            "and records `{ ok: true }` when the correction goes through, which is what "
            "this rule is about: check whether RF-22 moved, and rewrite it here."
        )

    def test_the_success_message_can_be_read(self) -> None:
        """A correction that worked has to leave something on screen that says so.

        Either the run that succeeds does not close the dialog, or what the
        dialog renders while closed shows the outcome as well. Taking both
        decisions at once — write the message, then close — is the one
        combination that leaves the person with nothing: the correction was
        applied, the row refreshes, and RF-22's «se aplicó» never appears.
        """
        # Arrange
        dialog = read_dialog()
        assert dialog is not None, "guarded by test_it_hides_itself_and_reports_a_result"

        # Act
        on_success = what_runs_on_success(dialog.on_submit)
        closes_on_success = dialog.closes_itself.search(on_success) is not None
        readable_while_closed = re.search(rf"\b{dialog.outcome}\b", dialog.while_closed) is not None

        # Assert
        assert not closes_on_success or readable_while_closed, (
            f"{DIALOG.name} writes the outcome to `{dialog.outcome}` and, in the same run, "
            f"sets `{dialog.flag}` to false — and what it renders while closed never reads "
            f"`{dialog.outcome}`. So the person who corrected a value watches the dialog "
            "vanish and finds the confirmation nowhere: RF-22 answers when an action fails, "
            "because a failure leaves the dialog open, and says nothing when it works."
        )
