"""The single screen of loads and corrections, checked against the real rules.

RF-20 asks for one screen that gathers every load and correction, and RF-21
that each person is offered only theirs. Both answers live in
`frontend/lib/operations/actions.ts`: a typed registry where each action
declares the section its route already demands and whether it demands the level
to write, plus `actionsFor()`, which filters it by the permission map the
backend hands out with the session.

Why a Python test for TypeScript: the frontend has no test runner, and adding
one to hold a couple of static rules is a bigger change than they deserve — the
same reasoning as `test_auth_pages.py` and `test_dates_have_a_timezone.py`. If
a frontend suite ever exists, this belongs there.

What could not be checked from the browser side anyway is the half that matters
here. The registry names a section as a **string**, and the only thing that
says whether that string is a real part of the business is
`app.modules.identity.permissions.Section`, in Python. The TypeScript union
comes from `lib/api/types.ts`, a generated file that is checked in and
regenerated by hand, so it can lag behind the enum it was generated from — and
an invented section does not fail loudly: `canEdit` reads `undefined` from the
permission map, calls it `NONE`, and the action disappears for **everybody**,
including the owner. A screen that quietly offers nothing looks exactly like a
screen whose feature was never built.

So the questions this file asks are the ones the matrix answers:

1. every section the registry names exists;
2. purchasing and sales are offered **different** sets, and neither of them is
   empty — the case `/analyze` raised as H-1, because a registry that only
   listed the two actions 003 brings would leave whoever handles purchasing
   opening the screen to nothing;
3. the owner is offered all of them;
4. every action's `href` lands on a page that exists, because an action whose
   screen is not there is a dead card that still counts as "purchasing has
   something".

And two more about the code rather than the registry: that the screen filters
by the session instead of listing the actions itself, and that `actionsFor()`
asks `canEdit` for a writing action and `canSee` for a reading one. That last
rule is written twice — once in TypeScript and once, as `offered_to()` below,
in Python — and two copies of a rule are one rule and one bug unless something
holds them together.

None of this is the permission. The refusal lives in the route — every endpoint
declares its own authorisation and `test_route_authorization.py` says so. This
file checks that what is *offered* agrees with what would be *allowed*, which
is a different failure: an action offered to somebody the route will refuse, or
hidden from somebody the route would admit.

RF-22 closes the same screen and is the last section here: an action that
finishes has to tell whoever ran it whether it was applied or whether it
failed. That one is not about the registry but about the components where a
correction is actually made and undone — and it is checked the same way, and
for the same reason, because it is the same missing test runner. Those
components are searched for rather than named, which is the lesson of how RF-22
was missed: the rule was right and one of the two screens was simply never
inside it. The search covers `@/app/actions/corrections`; what it still leaves
out — a registered action of this feature run through another Server Action
module — and what no reading of the source can settle — whether a successful
run takes the component off the screen — are both written down where the search
is defined, because a gap nobody wrote down is the same mistake again.
"""

import re
from dataclasses import dataclass
from pathlib import Path

import pytest

import app
from app.modules.identity.permissions import Level, Section, level_for

REPOSITORY_ROOT = Path(app.__file__).resolve().parents[2]
REGISTRY = REPOSITORY_ROOT / "frontend" / "lib" / "operations" / "actions.ts"
PRIVATE_PAGES = REPOSITORY_ROOT / "frontend" / "app" / "(private)"
SCREEN = PRIVATE_PAGES / "acciones" / "page.tsx"

# The three roles, spelled as `permissions.MATRIX` keys them. `UserRole` lives
# inside `identity` and stays there: the matrix is keyed by plain strings on
# purpose, and this file only reads it.
OWNER = "OWNER"
PURCHASING = "PURCHASING"
SALES = "SALES"

# `export const MANUAL_ACTIONS: readonly ManualAction[] = [ ... ]`, up to the
# closing bracket in the first column. `[^=]*` walks past the type annotation,
# whose own `[]` would otherwise be mistaken for the array.
MANUAL_ACTIONS = re.compile(
    r"^export const MANUAL_ACTIONS[^=]*=\s*\[(.*?)^\]", re.DOTALL | re.MULTILINE
)
# One entry, as a whole object literal. `[^{}]*` cannot leave the braces it
# opened, so a field is only ever read from the action that declares it — and
# each field is then found on its own, in any order. TypeScript does not fix
# the order of an object's properties, and a parse that assumed one would skip
# an entry written differently instead of failing: the action would vanish
# from every test in this file, H-1's guard included.
ENTRY = re.compile(r"\{(?P<body>[^{}]*)\}", re.DOTALL)
FIELDS = {
    "id": re.compile(r"\bid:\s*'(?P<value>[^']+)'"),
    "href": re.compile(r"\bhref:\s*'(?P<value>[^']+)'"),
    "section": re.compile(r"\bsection:\s*'(?P<value>[^']+)'"),
    "writes": re.compile(r"\bwrites:\s*(?P<value>true|false)"),
}
# How many entries were declared, whatever shape they were written in — the
# count `registry()` has to match.
DECLARED = re.compile(r"^\s+id:", re.MULTILINE)

# What the screen must do with the registry, and what it must not do instead.
FILTERS_BY_SESSION = re.compile(r"actionsFor\s*\(\s*session\.permissions\s*\)")
LISTS_THEM_ITSELF = re.compile(r"\bMANUAL_ACTIONS\b")
# The rule `offered_to()` reimplements below, pinned on the TypeScript side so
# the two cannot drift: a swapped `canEdit`/`canSee` would leave every test in
# `TestEachRoleIsOfferedItsOwnActions` green while the screen offered actions
# the route refuses.
THE_LEVEL_IT_DEMANDS = re.compile(
    r"action\.writes\s*\?\s*canEdit\(\s*permissions\s*,\s*action\.section\s*\)"
    r"\s*:\s*canSee\(\s*permissions\s*,\s*action\.section\s*\)"
)


@dataclass(frozen=True, slots=True)
class RegisteredAction:
    """One line of the registry, as far as authorisation is concerned."""

    id: str
    href: str
    section: str
    writes: bool


def registry_source() -> str:
    """`actions.ts`, whole."""
    return REGISTRY.read_text(encoding="utf-8")


def declared_block() -> str:
    """The body of the `MANUAL_ACTIONS` array, or nothing if its shape moved."""
    listed = MANUAL_ACTIONS.search(registry_source())
    return listed.group(1) if listed is not None else ""


def registry() -> list[RegisteredAction]:
    """Every action declared in `actions.ts` that could be read whole.

    An entry missing one of the four fields is left out rather than guessed at,
    and `test_every_entry_was_read` is what turns that silence into a failure.
    """
    actions = []
    for entry in ENTRY.finditer(declared_block()):
        found = {name: pattern.search(entry["body"]) for name, pattern in FIELDS.items()}
        if any(field is None for field in found.values()):
            continue
        actions.append(
            RegisteredAction(
                id=found["id"]["value"],
                href=found["href"]["value"],
                section=found["section"]["value"],
                writes=found["writes"]["value"] == "true",
            )
        )
    return actions


def section_of(action: RegisteredAction) -> Section:
    """The action's section as the business knows it, or say it is invented."""
    try:
        return Section(action.section)
    except ValueError:
        pytest.fail(f"«{action.id}» declares a section that does not exist: {action.section!r}")


def offered_to(role: str) -> set[str]:
    """The actions this role would be shown, by the rule the screen applies.

    `actionsFor()` asks `canEdit` for a writing action and `canSee` for a
    reading one, over the map `permissions_for(role)` builds — which is
    `level_for` on every section. So this is the same question, asked of the
    matrix the backend actually enforces rather than of a copy of it.
    """
    return {
        action.id
        for action in registry()
        if level_for(role, section_of(action)) >= (Level.WRITE if action.writes else Level.READ)
    }


@pytest.mark.unit
class TestTheRegistryNamesRealSections:
    """A section that does not exist hides its action from everybody."""

    def test_there_are_actions_to_check(self) -> None:
        """A moved file or a renamed constant must not quietly pass this file."""
        # Arrange / Act
        actions = registry()

        # Assert
        assert actions, f"no MANUAL_ACTIONS entries parsed out of {REGISTRY}"

    def test_every_entry_was_read(self) -> None:
        """An action this file could not parse must break it, not disappear.

        Every other test here counts what `registry()` returns, so an entry
        skipped is an entry nobody checks: its section is never validated, its
        page is never looked for, and the owner test compares the shortened
        list against itself and passes.
        """
        # Arrange / Act
        declared = len(DECLARED.findall(declared_block()))

        # Assert
        assert len(registry()) == declared, (
            f"{declared} actions are declared and {len(registry())} could be read: "
            "one of them is written in a shape this file does not parse, and is "
            "silently going unchecked."
        )

    def test_no_two_actions_share_an_id(self) -> None:
        """The id is the React key, and the name the rest of this file counts by."""
        # Arrange / Act
        ids = [action.id for action in registry()]

        # Assert
        assert len(ids) == len(set(ids)), f"repeated action ids in the registry: {ids}"

    @pytest.mark.parametrize("action", registry(), ids=lambda action: action.id)
    def test_its_section_exists(self, action: RegisteredAction) -> None:
        """Otherwise the permission map answers `undefined`, read as `NONE`."""
        # Arrange
        sections = {section.value for section in Section}

        # Assert
        assert action.section in sections, (
            f"«{action.id}» declares a section that does not exist: {action.section!r}. "
            "The permission map has no entry for it, `canEdit` reads it as NONE, and "
            "the action disappears for everybody, the owner included."
        )


@pytest.mark.unit
class TestEveryActionLeadsSomewhere:
    """RF-20: the single screen is a launcher, and a launcher can misfire."""

    @pytest.mark.parametrize("action", registry(), ids=lambda action: action.id)
    def test_its_page_exists(self, action: RegisteredAction) -> None:
        """The action is done on the screen its `href` points at, so it has to be there.

        A card that leads to a 404 still counts as an action offered: whoever
        handles purchasing would be told they have something to do and find
        nothing when they press it, and `test_purchasing_is_offered_something`
        would go on saying the screen is fine.
        """
        # Arrange / Act
        page = PRIVATE_PAGES / action.href.strip("/") / "page.tsx"

        # Assert
        assert page.exists(), (
            f"«{action.id}» is offered at {action.href}, and there is no page there: {page}"
        )


@pytest.mark.unit
class TestEachRoleIsOfferedItsOwnActions:
    """RF-21, resolved against the matrix rather than against a second copy."""

    def test_it_asks_for_the_level_the_action_demands(self) -> None:
        """The rule `offered_to()` reimplements, read off `actionsFor()` itself.

        The four tests below ask the matrix what each role would be offered,
        using a Python copy of the filter. Nothing else says the TypeScript
        still filters that way: swap `canEdit` for `canSee` and every one of
        them stays green while the screen offers a writing action to somebody
        who may only read it — and the route, which is the real permission,
        answers 403 when they press it.
        """
        # Arrange / Act
        source = registry_source()

        # Assert
        assert THE_LEVEL_IT_DEMANDS.search(source), (
            "`actionsFor()` no longer asks canEdit for a writing action and canSee "
            "for a reading one, so what this file checks is no longer the rule the "
            "screen applies."
        )

    def test_purchasing_is_offered_something(self) -> None:
        """The H-1 case: a registry holding only 003's actions leaves them nothing.

        Prices and the review queue are purchasing's, the product catalog and
        undoing a correction are not — so if the registry ever narrowed to what
        this feature added, Marcela would open the single screen and read that
        her access has no actions at all.
        """
        # Arrange / Act
        purchasing = offered_to(PURCHASING)

        # Assert
        assert purchasing, (
            "whoever handles purchasing opens the one screen of loads and "
            "corrections and is offered nothing: the registry lost the actions "
            "that are theirs."
        )

    def test_sales_is_offered_something(self) -> None:
        """And the same for Julián, whose section is the catalog."""
        # Arrange / Act
        sales = offered_to(SALES)

        # Assert
        assert sales, (
            "whoever handles sales opens the one screen of loads and corrections "
            "and is offered nothing."
        )

    def test_the_two_sets_are_different(self) -> None:
        """RF-21 literally: the screen shows Marcela actions Julián does not get.

        Different in both directions, which is the reading that means anything:
        one set being a subset of the other would satisfy `!=` while still
        offering the smaller role a strictly poorer version of the same screen.
        """
        # Arrange / Act
        purchasing = offered_to(PURCHASING)
        sales = offered_to(SALES)

        # Assert
        assert purchasing - sales, (
            f"purchasing is offered nothing sales is not: {sorted(purchasing)}"
        )
        assert sales - purchasing, f"sales is offered nothing purchasing is not: {sorted(sales)}"

    def test_the_owner_is_offered_all_of_them(self) -> None:
        """The owner reaches every section, so the screen hides nothing from them."""
        # Arrange
        everything = {action.id for action in registry()}

        # Act
        owner = offered_to(OWNER)

        # Assert
        assert owner == everything, (
            f"the owner is not offered {sorted(everything - owner)}, and reaches every section"
        )


@pytest.fixture(scope="module")
def screen_source() -> str:
    """The source of the single screen, read once."""
    return SCREEN.read_text(encoding="utf-8")


@pytest.mark.unit
class TestTheScreenFiltersByTheSession:
    """RF-20: one screen, and the list on it is the session's, not a fixed one."""

    def test_the_screen_exists(self) -> None:
        """RF-20 is a route before it is anything else."""
        # Assert
        assert SCREEN.exists(), f"{SCREEN} is the single screen RF-20 asks for"

    def test_it_asks_the_registry_what_this_session_may_do(self, screen_source: str) -> None:
        """`actionsFor(session.permissions)` and not a list written by hand."""
        # Assert
        assert FILTERS_BY_SESSION.search(screen_source), (
            "the actions screen does not filter the registry by the session's "
            "permissions, so it shows everybody the same list (RF-21)."
        )

    def test_it_does_not_reach_past_the_filter(self, screen_source: str) -> None:
        """Rendering `MANUAL_ACTIONS` directly would put the filter out of the way."""
        # Assert
        assert not LISTS_THEM_ITSELF.search(screen_source), (
            "the actions screen names MANUAL_ACTIONS: whatever it renders from "
            "it is unfiltered, and offers actions the route will refuse."
        )


# --- RF-22: an action that finishes says whether it was applied -------

# Where a manual action of this feature actually finishes in front of somebody:
# every component that calls one of the correction Server Actions. They are
# searched for rather than listed, and that is the point — 003 added two of
# these and only the first one was ever checked here, so the second went on
# saying nothing for as long as it did. A third correction written against
# `@/app/actions/corrections` lands in this test the day it is written, without
# anybody remembering to add it.
#
# Two things this section does **not** decide, written down because a gap
# nobody wrote down is how RF-22 got missed twice:
#
# 1. A manual action run through another Server Action module.
#    `resolve-triage-case` is one: `MANUAL_ACTIONS` above registers it as an
#    action of this feature, and `CaseCard` refreshes on success without saying
#    anything, which is letter for letter the defect this section exists for.
#    It is left out because covering it is two changes and not one — that
#    component has to say that it was applied, and these rules have to learn a
#    third honest channel first: `UpdateNowButton`, the other registered action
#    outside this module, reports both outcomes in an `outcome` state that is
#    neither `{ ok: true }` nor a toast, and a rule that only knows those two
#    would fail correct code. Until both land, this is a hole and not a
#    boundary the file earned.
#
# 2. Whether a successful run leaves the component mounted. Nothing in the
#    source answers it: `router.refresh()` re-renders the page, and whether the
#    component survives depends on whether the refreshed page still lists the
#    row it hangs off. `RevertCorrectionButton` does not survive its own
#    success and announces to the toaster for that reason — a judgement made by
#    whoever wrote it, which this file cannot check. What it checks is the half
#    that is written down: a verdict kept in the component's own state is
#    rendered by everything that component can put on screen.
FRONTEND = REPOSITORY_ROOT / "frontend"
COMPONENTS = FRONTEND / "components"
APP = FRONTEND / "app"
LAYOUT = APP / "layout.tsx"

# `import { correctProduct, … } from '@/app/actions/corrections'`. This is the
# discovery too, and not a plain substring search. What was imported still has
# to be filtered: a file that imports only a **type** from there executes
# nothing, and would be dragged in to fail a rule that has nothing to say about
# it. A type hides under two spellings — `import type { X }`, which this pattern
# does not match at all, and `import { type X }`, which it does match and
# `correction_actions_in()` drops.
#
# Two modules and not one. The rule is about **manual actions**, which is what
# `frontend/lib/operations/actions.ts` enumerates, not about corrections in
# particular — and reading only the corrections module is exactly how the same
# defect survived in `CaseCard` after being fixed twice next door: resolving a
# case is one of the four manual actions 003 published, and it imports from
# `@/app/actions/triage`.
#
# `@/app/actions/prices` is the fourth and is deliberately still out. Its
# component does report both outcomes, through a third shape neither channel
# here recognises; teaching the rule that shape is a change to the rule, not to
# the component, and it does not belong in the same edit as a defect fix.
ACTION_MODULES = ("corrections", "triage")
# The module is not the unit: `@/app/actions/triage` also exports the rule and
# alias management of 001, whose components are not manual actions of the
# registry and have nothing to do with this rule. What the rule is about is the
# actions `frontend/lib/operations/actions.ts` publishes as 003's, so those are
# named here — by their **exported** name, which is what survives an alias.
THE_FOUR = frozenset({"correctProduct", "revertCorrection", "resolveCase"})
CORRECTION_ACTIONS = re.compile(
    r"^import\s*\{(?P<names>[^}]*)\}\s*from\s*'@/app/actions/(?:"
    + "|".join(ACTION_MODULES)
    + r")'",
    re.MULTILINE,
)
# `type CorrectionOutcome` inside the braces: a name that exists for the type
# checker and never runs.
A_TYPE = re.compile(r"^type\s+\w")
IDENTIFIER = re.compile(r"\b\w+\b")

# --- reading a component ----------------------------------------------------

# Where a function's body starts is worked out by walking past its parameter
# list, never by taking the first brace after the keyword. A destructured
# parameter — `async ({ id }: { id: number }) => {` — opens two braces of its
# own before the body ever begins, and a reading that took the first one would
# call the destructuring the function: the run would come back as ` id `, the
# call inside it would belong to no run at all, and the rules below would fail
# a component that is perfectly correct.
ASYNC = re.compile(r"\basync\b")
# The name of a declaration, when there is one: `async function onClick(`. The
# `\w*` also swallows the lone parameter of `async id => …`, which is harmless —
# what comes next is read the same way in both cases.
A_NAME = re.compile(r"\s*(?:function\s+)?\w*\s*")
# What separates a parameter list from the body: a return type annotation, an
# arrow, or nothing at all.
THE_BODY = re.compile(r"\s*(?::[^={;]*)?(?:=>\s*)?\{")
# The two ways this repository declares a function that could be a component.
A_DECLARATION = re.compile(r"\bfunction\s+\w+\s*(?=\()")
AN_ASSIGNMENT = re.compile(r"\b(?:const|let)\s+\w+\s*(?::[^=;]*)?=\s*(?:async\s+)?(?=[(\w])")
RETURNS = re.compile(r"\breturn\b")
# `return ( … )` — one of the things a component can put on screen. Prettier
# wraps every multi-line JSX in those parentheses, so this is how the repository
# writes them; a `return <span/>` on one line is not read, and
# `test_what_the_screen_can_render_was_found` is what says so out loud instead
# of letting the rule below quietly check nothing.
RETURNS_JSX = re.compile(r"\breturn\s*\(")
# `if (result.ok) { … }` — the branch that only runs when it worked. Told from
# `if (!result.ok)`, which guards the opposite branch, by forbidding the `!`
# rather than by spelling the whole condition: what matters is which side of the
# test the code sits on.
SUCCEEDED = re.compile(r"if\s*\(\s*[^()!]*\.ok\b[^()]*\)\s*\{")
# `setSomething({ ok: true, … })` — recording that it was applied in the
# component's own state. The setter is captured because the state it writes is
# what the JSX renders, and the name of that state follows from it.
RECORDS_SUCCESS = re.compile(r"\b(?P<setter>set[A-Z]\w*)\(\s*\{[^{}]*\bok:\s*true\b[^{}]*\}\s*\)")
# The other honest channel: saying it out loud, to something that is not this
# component. Either spelling of the project's helper counts.
ANNOUNCES_SUCCESS = re.compile(
    r"\baddToast\(\s*\{[^{}]*\btype:\s*'success'[^{}]*\}|\btoast\.success\s*\("
)
# `<Toaster />` in the root layout: where an announcement is rendered, and the
# reason it survives the component that made it.
TOASTER_IS_MOUNTED = re.compile(r"<Toaster\b")

PAIRS = {"{": "}", "(": ")"}


def balanced_block(source: str, opening: int) -> str:
    """What lies between the bracket at `opening` and the one that closes it."""
    opened = source[opening]
    closed = PAIRS[opened]
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == opened:
            depth += 1
        elif source[index] == closed:
            depth -= 1
            if depth == 0:
                return source[opening + 1 : index]
    return ""


def body_after_parameters(source: str, at: int) -> tuple[int, str] | None:
    """The `{ … }` a function opens after its parameter list, and where it opens.

    `at` is just past the function's name, on its parameter list if it has one.
    The list is skipped as a balanced pair, which is the whole point of reading
    it this way rather than jumping to the next brace: the parameters may open
    braces of their own.

    Nothing means this is not a function — the same walk runs over every `const`
    in the file, and most of them are not.
    """
    if source[at : at + 1] == "(":
        at += len(balanced_block(source, at)) + 2
    body = THE_BODY.match(source, at)
    if body is None:
        return None
    opening = body.end() - 1
    return opening, balanced_block(source, opening)


def blocks(source: str, starts: list[int]) -> list[tuple[int, int, str]]:
    """The body each of those functions opens, as (start, end, code)."""
    found = []
    for at in starts:
        body = body_after_parameters(source, at)
        if body is None:
            continue
        opening, code = body
        found.append((opening + 1, opening + 1 + len(code), code))
    return found


def past_the_name(source: str, at: int) -> int:
    """Where a function's name ends, which is `at` when it has none.

    Every piece of `A_NAME` is optional, so the match is always there — but an
    arrow written inline in the JSX has no name to walk past, and saying that
    out loud is cheaper than a reader working out that the empty match is legal.
    """
    name = A_NAME.match(source, at)
    return name.end() if name is not None else at


def async_runs(source: str) -> list[tuple[int, int, str]]:
    """Every `async … { … }`: a named function, an assigned arrow, or one in the JSX.

    Which of them runs an action is decided by what it calls, never by what it
    is called.
    """
    return blocks(source, [past_the_name(source, found.end()) for found in ASYNC.finditer(source)])


def functions(source: str) -> list[tuple[int, int, str]]:
    """Every function in the file, however it was declared."""
    return blocks(
        source,
        [
            found.end()
            for pattern in (A_DECLARATION, AN_ASSIGNMENT)
            for found in pattern.finditer(source)
        ],
    )


def what_runs_on_success(code: str) -> str:
    """The code with every branch that returns early taken out of it.

    What is left is what a run that reaches the end executes, whatever order the
    statements were written in. That is the whole point of asking it this way:
    the rules below are about which decisions a component takes together, not
    about which line sits under which.
    """
    kept: list[str] = []
    index = 0
    while index < len(code):
        if code[index] == "{":
            body = balanced_block(code, index)
            if not RETURNS.search(body):
                kept.append("{" + what_runs_on_success(body) + "}")
            index += len(body) + 2
            continue
        kept.append(code[index])
        index += 1
    return "".join(kept)


def what_a_successful_run_does(run: str) -> str:
    """Everything the run executes when the action worked, both guards allowed.

    A component may test the failure and return —`if (!result.ok) { … return }`—
    and speak afterwards, or test the success and speak inside it before
    returning. Those are the same behaviour written two ways, so both are read:
    the trimmed path for the first, the success-guarded blocks for the second.

    What is left out is what only ever runs when it failed. That matters:
    reading the run whole would count a message written inside
    `if (!result.ok)` as an answer to RF-22, and telling somebody it was applied
    on the way to telling them it was not is not an answer to anything.
    """
    reached = [what_runs_on_success(run)]
    reached += [balanced_block(run, found.end() - 1) for found in SUCCEEDED.finditer(run)]
    return "".join(reached)


def correction_actions_in(source: str) -> list[str]:
    """The correction actions a file imports in order to *run* them.

    A specifier marked `type` is dropped: it executes nothing, and a file that
    imported only one of those would be pulled into every rule below and fail
    `test_the_run_that_finishes_it_was_found` for having no run to read. Today
    `app/actions/corrections.ts` exports no type, so nothing is being excluded —
    which is exactly why it is worth writing down before one is exported.

    An aliased import is taken by its alias, because that is the name the calls
    in this file are written with.
    """
    names: list[str] = []
    for imported in CORRECTION_ACTIONS.finditer(source):
        for specifier in imported["names"].split(","):
            specifier = specifier.strip()
            if not specifier or A_TYPE.match(specifier):
                continue
            identifiers = IDENTIFIER.findall(specifier)
            # The **first** identifier decides whether this is one of the four,
            # because that is the exported name; the **last** is what the calls
            # in this file are written with, aliased or not.
            if identifiers and identifiers[0] in THE_FOUR:
                names.append(identifiers[-1])
    return names


def runs_that_finish_an_action(source: str) -> list[str]:
    """The body of every async run that calls one of the correction actions.

    The *innermost* one around each call, so a handler is read whole and once
    even when it was written inside another function — and so a component that
    finishes two different actions is checked on both.
    """
    called = [
        call.start()
        for name in correction_actions_in(source)
        for call in re.finditer(rf"\b{name}\s*\(", source)
    ]
    if not called:
        return []
    runs = async_runs(source)
    innermost: dict[tuple[int, int], str] = {}
    for at in called:
        holding = [run for run in runs if run[0] <= at < run[1]]
        if holding:
            start, end, body = min(holding, key=lambda run: run[1] - run[0])
            innermost[(start, end)] = body
    return list(innermost.values())


def what_holds(source: str, run: str) -> str:
    """The whole component a run lives in, its JSX included.

    The outermost function around it, because the run is a handler declared
    inside the component and what has to show the verdict is what the
    *component* returns. Read this way, a helper component written in the same
    file — `Outcome`, beside `CorrectionDialog` — is not mistaken for it.
    """
    at = source.find(run)
    holding = [body for start, end, body in functions(source) if start <= at < end]
    return max(holding, key=len) if holding else ""


def what_it_can_render(component: str) -> tuple[str, ...]:
    """Every `return ( … )` of that component: each thing it can put on screen."""
    return tuple(
        balanced_block(component, found.end() - 1) for found in RETURNS_JSX.finditer(component)
    )


def state_behind(setter: str) -> str:
    """The state a setter writes to: `setMessage` → `message`."""
    return setter[3].lower() + setter[4:]


def says_it_was_applied(run: str) -> bool:
    """Whether this run leaves anything behind that says the action worked.

    Two honest channels: record `{ ok: true }` for the component's own JSX to
    render, or announce it to the toaster in the root layout. A run that does
    neither answers only half of RF-22 — and one that does either of them only
    on the way out of a failure answers neither half.
    """
    on_success = what_a_successful_run_does(run)
    return bool(RECORDS_SUCCESS.search(on_success) or ANNOUNCES_SUCCESS.search(on_success))


@dataclass(frozen=True, slots=True)
class Run:
    """One run through which a manual action ends, as far as RF-22 is concerned."""

    body: str
    """The run whole, failure branches and all."""

    on_success: str
    """Everything it does when the action worked, whichever way its guard is written."""

    branches: tuple[str, ...]
    """Every JSX its component can return.

    Not the branch that shows *after* this run: which one that is depends on
    state this file cannot evaluate, and deciding it from the shape of an `if`
    is what quietly stopped applying before. So the verdict is asked of all of
    them, and a component that cannot honestly answer that has the toaster.
    """


@dataclass(frozen=True, slots=True)
class FinishedAction:
    """A component where a manual action ends, read as these rules need it."""

    path: Path
    runs: tuple[Run, ...]


def screens_that_finish_a_correction() -> list[Path]:
    """Every component through which one of 003's corrections is executed."""
    return [
        path
        for root in (COMPONENTS, APP)
        for path in sorted(root.rglob("*.tsx"))
        if correction_actions_in(path.read_text(encoding="utf-8"))
    ]


def read_screen(path: Path) -> FinishedAction | None:
    """One of those components, or nothing if no run of it calls the action.

    Nothing means the component stopped being the shape these rules talk about,
    and `test_the_run_that_finishes_it_was_found` is what turns that into a
    failure instead of a rule that quietly stops applying.
    """
    source = path.read_text(encoding="utf-8")
    runs = runs_that_finish_an_action(source)
    if not runs:
        return None
    return FinishedAction(
        path=path,
        runs=tuple(
            Run(
                body=run,
                on_success=what_a_successful_run_does(run),
                branches=what_it_can_render(what_holds(source, run)),
            )
            for run in runs
        ),
    )


@pytest.mark.unit
class TestTheResultOfACorrectionReachesTheScreen:
    """RF-22: an action that finishes tells whoever ran it how it went.

    The backend half is covered by `test_action_outcomes.py`: the refusals, and
    the correction that goes through. What no test says is that the answer
    arrives in front of the person, and that is the half worth checking here —
    an outcome the API returned and the screen never showed is, from the desk
    where the work happens, indistinguishable from nothing having happened.

    003 brought two components where a correction is executed: the one that
    corrects a value and the one that undoes that correction. They are not named
    here one by one, they are looked for, because the way this went wrong the
    first time was not that somebody wrote the rule badly — it was that the
    second button was never inside it.

    Why a Python test for TSX: the same reason as the rest of this file — the
    frontend has no runner. And why it is written against the code's decisions
    rather than its lines: a static reading of a component is only worth having
    if it survives the component being rearranged. The question asked is the
    behaviour — *can the person read that it worked?* — and there are two honest
    answers to it. Keep the verdict in the component's own state, and render it
    from everything the component can put on screen; or announce it to the
    toaster in the root layout, which outlives the component that spoke. The one
    that does not pass is the component that says nothing.

    **Which of the two a component owes is not decided here.** The toaster is
    what a component has to use when its own success takes it off the screen,
    and nothing in the source says whether a refresh does that — that hole is
    written down above `FRONTEND`, and it is the reason this class cannot claim
    that `RevertCorrectionButton` announces for the right reason, only that it
    announces. What is enforced is the half that *is* written down, and it is
    deliberately strict: a verdict written into state has to be readable from
    every branch, because working out which branch shows after the run is the
    reasoning that silently stopped applying. A component with a branch that has
    nothing to do with the correction has the toaster.

    Rearranged includes the shape of the guard. A component may test the failure
    and return —`if (!result.ok) { … return }`— and speak afterwards, or test
    the success and speak inside it before returning. `what_a_successful_run_does`
    reads both, and reads neither the code that only runs when it failed.
    """

    def test_there_are_screens_to_check(self) -> None:
        """A move or a rename must not quietly turn this whole rule off."""
        # Arrange / Act
        screens = screens_that_finish_a_correction()

        # Assert
        assert screens, (
            "no component calls the correction actions any more: RF-22's two "
            f"screens are not under {COMPONENTS} nor {APP}, and this rule is "
            "checking nothing. Find where a correction is confirmed now."
        )

    @pytest.mark.parametrize("path", screens_that_finish_a_correction(), ids=lambda path: path.name)
    def test_the_run_that_finishes_it_was_found(self, path: Path) -> None:
        """A component this file cannot read must break it, not disappear.

        Both rules below are asked of the run that calls the action. If that
        run cannot be found — the call moved out of an async function, or into
        a shape this file does not parse — they have nothing to say and would
        say it in green.
        """
        # Assert
        assert read_screen(path) is not None, (
            f"{path.name} imports a correction action and no async run of it calls "
            "one: RF-22 is no longer checked on this screen. Find where the action "
            "is executed now, and rewrite this rule around it rather than dropping it."
        )

    @pytest.mark.parametrize("path", screens_that_finish_a_correction(), ids=lambda path: path.name)
    def test_what_the_screen_can_render_was_found(self, path: Path) -> None:
        """And neither may the half that says *where the verdict is read*.

        `test_the_success_message_can_be_read` compares the verdict against the
        JSX the component returns. If none was found — the component is written
        in a shape this file does not walk, or its JSX is returned without the
        parentheses Prettier puts there — that comparison is against an empty
        list, which passes for free. This is the guard that broke when the rule
        was last rewritten, and it is what keeps it from being rewritten away
        again: the parse failing has to look like a failure.
        """
        # Arrange
        screen = read_screen(path)
        assert screen is not None, "guarded by test_the_run_that_finishes_it_was_found"

        # Act / Assert
        for run in screen.runs:
            assert run.branches, (
                f"{path.name} finishes a manual action and this file found nothing it "
                "can render: it walks `function Name(…)` and `const Name = (…) =>`, and "
                "reads what they `return ( … )`. The component is written some other "
                "way, so the rule about where the verdict can be read is comparing "
                "against nothing. Teach this file that shape rather than leaving it green."
            )

    @pytest.mark.parametrize("path", screens_that_finish_a_correction(), ids=lambda path: path.name)
    def test_it_says_that_it_was_applied(self, path: Path) -> None:
        """A run that succeeds has to leave something that says so.

        This is the half RF-22 lost twice. A component that only ever writes
        the failure answers «si falló» and stays silent on «si se aplicó»: the
        person presses the button, the row refreshes, and the only difference
        between it having worked and nothing having happened is that the button
        is gone.
        """
        # Arrange
        screen = read_screen(path)
        assert screen is not None, "guarded by test_the_run_that_finishes_it_was_found"

        # Act / Assert
        for run in screen.runs:
            assert says_it_was_applied(run.body), (
                f"{path.name} finishes a manual action and its successful run says "
                "nothing: it neither records `{ ok: true }` for its own JSX to render "
                "nor announces it to the toaster. RF-22 asks for «si se aplicó o si "
                "falló», and this screen only ever answers the second half."
            )

    @pytest.mark.parametrize("path", screens_that_finish_a_correction(), ids=lambda path: path.name)
    def test_the_success_message_can_be_read(self, path: Path) -> None:
        """And a verdict kept in state has to be rendered wherever it can be needed.

        Writing `{ ok: true }` into a state that no JSX reads puts the
        confirmation in a variable; hiding the one branch that reads it puts the
        confirmation behind a form nobody reopens. They are the same defect —
        the message exists and the person cannot get to it — and both are the
        same question: does everything this component can render read the
        verdict?

        Asked of every branch on purpose. Which branch shows after the run
        depends on state this file cannot evaluate, and the reading that tried
        to work it out from `if (!open)` stopped applying the day the condition
        was written differently. A component that has a branch with no business
        showing the verdict is not stuck: it announces to the toaster instead,
        and this rule never fires.
        """
        # Arrange
        screen = read_screen(path)
        assert screen is not None, "guarded by test_the_run_that_finishes_it_was_found"

        # Act / Assert
        for run in screen.runs:
            recorded = RECORDS_SUCCESS.search(run.on_success)
            if recorded is None:
                continue
            outcome = state_behind(recorded["setter"])
            silent = [branch for branch in run.branches if not re.search(rf"\b{outcome}\b", branch)]
            assert not silent, (
                f"{path.name} writes the verdict of a correction into `{outcome}`, and "
                f"{len(silent)} of the {len(run.branches)} things it can render never read "
                f"it. Whoever corrected a value lands on one of those and finds the "
                "confirmation nowhere: RF-22 answers when an action fails, because a "
                "failure leaves the form open, and says nothing when it works. Render "
                f"`{outcome}` from every branch, or announce the verdict to the toaster, "
                "which outlives this component."
            )

    def test_what_is_announced_is_rendered_somewhere(self) -> None:
        """The toaster is the other half of announcing, and it lives elsewhere.

        A screen that speaks to it is trusting a component in the root layout
        to be there. Take `<Toaster />` out of the layout and every one of those
        confirmations goes into a store nothing renders — with no error, and
        with this file otherwise green.
        """
        # Arrange
        announced = [
            screen.path
            for screen in map(read_screen, screens_that_finish_a_correction())
            if screen is not None and any(ANNOUNCES_SUCCESS.search(run.body) for run in screen.runs)
        ]
        if not announced:
            pytest.skip("no screen announces its outcome to the toaster")

        # Act / Assert
        assert TOASTER_IS_MOUNTED.search(LAYOUT.read_text(encoding="utf-8")), (
            f"{[path.name for path in announced]} announce that the action was applied "
            f"to the toaster, and {LAYOUT} no longer renders it: nothing on screen shows "
            "what they say."
        )


# Components written on purpose, to ask the rules above about shapes that are
# not in the repository today. They are the smallest thing that parses as what
# those rules look for: an import of a correction action and one async run that
# calls it.
SAYS_IT_INSIDE_THE_GUARD = """\
import { revertCorrection } from '@/app/actions/corrections'

export function Undo() {
  async function onClick() {
    const result = await revertCorrection(1)
    if (result.ok) {
      addToast({ type: 'success', title: 'Hecho', description: 'Volvió al valor del portal.' })
      router.refresh()
      return
    }
    setError(result.message)
  }
}
"""

SAYS_IT_AFTER_THE_GUARD = """\
import { revertCorrection } from '@/app/actions/corrections'

export function Undo() {
  async function onClick() {
    const result = await revertCorrection(1)
    if (!result.ok) {
      setError(result.message)
      return
    }
    addToast({ type: 'success', title: 'Hecho', description: 'Volvió al valor del portal.' })
    router.refresh()
  }
}
"""

SAYS_NOTHING = """\
import { revertCorrection } from '@/app/actions/corrections'

export function Undo() {
  async function onClick() {
    const result = await revertCorrection(1)
    if (result.ok) {
      router.refresh()
      return
    }
    setError(result.message)
  }
}
"""


SAYS_IT_ON_THE_WAY_OUT_OF_THE_FAILURE = """\
import { revertCorrection } from '@/app/actions/corrections'

export function Undo() {
  async function onClick() {
    const result = await revertCorrection(1)
    if (!result.ok) {
      addToast({ type: 'success', title: 'No se pudo deshacer', description: result.message })
      return
    }
    router.refresh()
  }
}
"""

A_DESTRUCTURED_PARAMETER = """\
import { revertCorrection } from '@/app/actions/corrections'

export function Undo() {
  const onClick = async ({ correctionId }: { correctionId: number }) => {
    const result = await revertCorrection(correctionId)
    if (!result.ok) {
      setError(result.message)
      return
    }
    addToast({ type: 'success', title: 'Hecho', description: 'Volvió al valor del portal.' })
  }

  return (
    <button onClick={() => onClick({ correctionId: 1 })}>Volver al valor del portal</button>
  )
}
"""

HIDES_THE_ONLY_PLACE_IT_SAYS_SO = """\
import { correctProduct } from '@/app/actions/corrections'

function Outcome({ ok, text }: { ok: boolean; text: string }) {
  return (
    <span className={ok ? 'ok' : 'bad'}>{text}</span>
  )
}

export function Correct() {
  if (!open) {
    return (
      <button onClick={() => setOpen(true)}>Corregir</button>
    )
  }

  async function onSubmit() {
    const result = await correctProduct({ productId: 1 })
    if (!result.ok) {
      setMessage({ ok: false, text: result.message })
      return
    }
    setMessage({ ok: true, text: 'Corregido.' })
    setOpen(false)
  }

  return (
    <form onSubmit={onSubmit}>{message && <Outcome ok={message.ok} text={message.text} />}</form>
  )
}
"""

SAYS_IT_WHEREVER_IT_ENDS_UP = """\
import { correctProduct } from '@/app/actions/corrections'

function Outcome({ ok, text }: { ok: boolean; text: string }) {
  return (
    <span className={ok ? 'ok' : 'bad'}>{text}</span>
  )
}

export function Correct() {
  if (!open) {
    return (
      <span>
        <button onClick={() => setOpen(true)}>Corregir</button>
        {message && <Outcome ok={message.ok} text={message.text} />}
      </span>
    )
  }

  async function onSubmit() {
    const result = await correctProduct({ productId: 1 })
    if (!result.ok) {
      setMessage({ ok: false, text: result.message })
      return
    }
    setMessage({ ok: true, text: 'Corregido.' })
    setOpen(false)
  }

  return (
    <form onSubmit={onSubmit}>{message && <Outcome ok={message.ok} text={message.text} />}</form>
  )
}
"""


def branches_around_the_run(source: str) -> tuple[str, ...]:
    """What the component holding the first run of `source` can put on screen."""
    return what_it_can_render(what_holds(source, runs_that_finish_an_action(source)[0]))


@pytest.mark.unit
class TestTheseRulesReadWhatTheyClaimTo:
    """The section above is a parser, and a parser that is wrong fails good code.

    Its rules run against whatever components happen to exist, so nothing else
    says they still accept the shapes they promise to accept — a component
    rearranged into one of them would look like a defect, and a rule that fails
    correct code is the shortest road to somebody weakening it (`TEST-06`).

    Every case pinned here was a real mistake of this file or of a reading of
    it: it read the success path where it meant to read the whole run, it called
    a type import a screen, it took the braces of a destructured parameter for a
    function body, and — for as long as it read the whole run — it would have
    taken a success message written on the way out of a failure for an answer to
    RF-22.
    """

    def test_a_run_that_says_it_inside_the_guard_answers_rf_22(self) -> None:
        """`if (result.ok) { addToast(…); return }` tells the person it worked.

        The same behaviour as the guard written the other way round, and the
        reading that trims every returning branch does not see it: the whole
        success path lives inside a block that returns.
        """
        # Arrange / Act
        runs = runs_that_finish_an_action(SAYS_IT_INSIDE_THE_GUARD)

        # Assert
        assert len(runs) == 1
        assert says_it_was_applied(runs[0]), (
            "a component that announces the success inside `if (result.ok)` is being "
            "read as saying nothing: the rule is failing correct code."
        )

    def test_a_run_that_says_it_after_the_guard_answers_rf_22(self) -> None:
        """And the other spelling, which is how the repository writes it today."""
        # Arrange / Act
        runs = runs_that_finish_an_action(SAYS_IT_AFTER_THE_GUARD)

        # Assert
        assert len(runs) == 1
        assert says_it_was_applied(runs[0])

    def test_a_run_that_only_writes_the_failure_does_not(self) -> None:
        """The defect itself, so widening the reading did not empty the rule."""
        # Arrange / Act
        runs = runs_that_finish_an_action(SAYS_NOTHING)

        # Assert
        assert len(runs) == 1
        assert not says_it_was_applied(runs[0]), (
            "a run that refreshes and says nothing is passing: the rule no longer "
            "catches the half of RF-22 it exists for."
        )

    def test_a_success_message_written_into_the_failure_does_not(self) -> None:
        """«Se aplicó» inside `if (!result.ok)` answers neither half of RF-22.

        The counterpart of reading the run whole. Widening the question to
        *does it say so anywhere* is right for a guard written either way round,
        and wrong the moment the message is on the branch that only runs when it
        failed: the run that succeeds still goes on saying nothing, and the one
        that fails says the opposite of what happened.
        """
        # Arrange / Act
        runs = runs_that_finish_an_action(SAYS_IT_ON_THE_WAY_OUT_OF_THE_FAILURE)

        # Assert
        assert len(runs) == 1
        assert not says_it_was_applied(runs[0]), (
            "a success message written inside `if (!result.ok)` is being counted as "
            "an answer to RF-22: the successful run says nothing and this rule agrees "
            "with it."
        )

    def test_a_destructured_parameter_is_not_the_body(self) -> None:
        """`async ({ id }: { id: number }) => {` opens braces before its body does.

        A reading that took the first brace after `async` would come back with
        the destructuring — ` correctionId ` — as the run, find the call to the
        action inside no run at all, and fail
        `test_the_run_that_finishes_it_was_found` on a component that answers
        RF-22 perfectly well.
        """
        # Arrange / Act
        runs = runs_that_finish_an_action(A_DESTRUCTURED_PARAMETER)

        # Assert
        assert len(runs) == 1, (
            "the run of a handler with a destructured parameter was not found: this "
            "file is about to fail correct code for the shape of its arguments."
        )
        assert says_it_was_applied(runs[0])

    def test_the_trimmed_success_path_still_drops_what_returns(self) -> None:
        """The other reading is unchanged, and both rules are built on it.

        `what_runs_on_success` is about decisions taken when the action worked,
        so it has to keep dropping every branch that returns — the one that
        reports the failure above all, which is what keeps a message written
        there from counting.
        """
        # Arrange / Act
        trimmed = what_runs_on_success(runs_that_finish_an_action(SAYS_IT_INSIDE_THE_GUARD)[0])

        # Assert
        assert "addToast" not in trimmed
        assert "setError" in trimmed

    def test_the_component_around_the_run_is_the_one_read(self) -> None:
        """Its own JSX, not a helper's, and not the handler's.

        `what_holds` takes the outermost function around the run, so a helper
        component written in the same file — `Outcome`, exactly as
        `CorrectionDialog` writes it — is not counted among the things the
        component can render. If it were, every rule below would demand that the
        helper read a state that is not its.
        """
        # Arrange / Act
        branches = branches_around_the_run(SAYS_IT_WHEREVER_IT_ENDS_UP)

        # Assert
        assert len(branches) == 2, (
            f"the component around the run was not read as the two things it can render: {branches}"
        )
        assert all("message" in branch for branch in branches), (
            "a component that renders the verdict from both of its branches is being "
            "read as hiding it: the rule is failing correct code."
        )

    def test_a_verdict_the_component_can_hide_is_caught(self) -> None:
        """And the defect: written into state, rendered from only one branch.

        The person corrects a value, the form closes, and the confirmation is
        left inside the branch that closing took away. This is asked without
        reading the condition that hides it, which is the point — the previous
        reading understood `if (!open)` and nothing else, so rewriting it as
        `if (open === false)` turned the rule off in silence.
        """
        # Arrange / Act
        branches = branches_around_the_run(HIDES_THE_ONLY_PLACE_IT_SAYS_SO)

        # Assert
        assert len(branches) == 2
        assert [branch for branch in branches if "message" not in branch], (
            "a component that writes the verdict and renders it from only one of its "
            "two branches is passing: the rule no longer catches the combination it "
            "exists for."
        )

    @pytest.mark.parametrize(
        ("source", "expected"),
        [
            ("import type { CorrectionOutcome } from '@/app/actions/corrections'", []),
            ("import { type CorrectionOutcome } from '@/app/actions/corrections'", []),
            (
                "import { type CorrectionOutcome, revertCorrection } "
                "from '@/app/actions/corrections'",
                ["revertCorrection"],
            ),
            (
                "import { correctProduct, revertCorrection } from '@/app/actions/corrections'",
                ["correctProduct", "revertCorrection"],
            ),
        ],
        ids=["import-type", "inline-type", "a-type-and-an-action", "two-actions"],
    )
    def test_a_type_is_not_an_action(self, source: str, expected: list[str]) -> None:
        """A name imported for the type checker runs nothing, in either spelling.

        This is what keeps a file that imports only a type out of the search. If
        it were dragged in, it would fail every rule below for having no run to
        read — and the rules have nothing to say about it.
        """
        # Arrange / Act / Assert
        assert correction_actions_in(source) == expected
