"""Cross-module communication.

`from app.shared.events import events, UserRegistered` is the only way one
module reaches another. See `bus.py` for the mechanics and `catalog.py` for the
vocabulary.
"""

from app.shared.events.bus import EventBus, Handler, discover_handlers, events
from app.shared.events.catalog import (
    AuditAction,
    BusinessParameterChanged,
    CorrectionConflicted,
    DomainEvent,
    JobRunFailed,
    JobRunSucceeded,
    KnownProductsMissing,
    ManualChangeRecorded,
    MissingProduct,
    NormalizedHistoryPoint,
    NormalizedPriceRow,
    PasswordResetRequested,
    PriceHistoryNormalized,
    PriceHistoryRowsQuarantined,
    PriceListExtracted,
    PriceListNormalized,
    PriceRowsQuarantined,
    PriceUpdateRecovered,
    PriceUpdateStalled,
    ProductHistoryExtracted,
    ProductPricesUpdated,
    ProductsRegistered,
    QuarantineCaseResolved,
    QuarantinedRow,
    QuarantineRuleRevoked,
    RegisteredProduct,
    UnknownProduct,
    UnknownProductsObserved,
    UserDeactivated,
    UserInvited,
    UserReactivated,
    UserRegistered,
    UserRoleChanged,
)

__all__ = [
    "AuditAction",
    "BusinessParameterChanged",
    "CorrectionConflicted",
    "DomainEvent",
    "EventBus",
    "Handler",
    "JobRunFailed",
    "JobRunSucceeded",
    "KnownProductsMissing",
    "ManualChangeRecorded",
    "MissingProduct",
    "NormalizedHistoryPoint",
    "NormalizedPriceRow",
    "PriceHistoryNormalized",
    "PriceHistoryRowsQuarantined",
    "PriceListExtracted",
    "PriceListNormalized",
    "PriceRowsQuarantined",
    "PriceUpdateRecovered",
    "PriceUpdateStalled",
    "ProductHistoryExtracted",
    "ProductPricesUpdated",
    "ProductsRegistered",
    "QuarantineCaseResolved",
    "QuarantineRuleRevoked",
    "QuarantinedRow",
    "RegisteredProduct",
    "UnknownProduct",
    "UnknownProductsObserved",
    "PasswordResetRequested",
    "UserDeactivated",
    "UserInvited",
    "UserReactivated",
    "UserRoleChanged",
    "UserRegistered",
    "discover_handlers",
    "events",
]
