"""Model registry.

Importing this module registers every mapped class with the declarative base, so
SQLAlchemy can resolve relationships and Alembic can autogenerate migrations.
Modules must never import models from each other: this file exists for the mapper,
not as a shortcut across module boundaries.

Every module adds its line here in the same commit as the migration that creates
its tables — `alembic check` runs in CI and fails on a model that no migration
accounts for.
"""

from app.modules.catalog.models import (
    AliasSource,
    CatalogSetting,
    Category,
    CategoryAlias,
    Correction,
    PricePoint,
    PriceSource,
    Product,
    ProductPrice,
    ProductStatus,
    StockPoint,
)
from app.modules.identity.models import (
    AccessEvent,
    AccessEventKind,
    AccessSetting,
    CredentialToken,
    Session,
    SessionRevocation,
    TokenPurpose,
    User,
    UserPassword,
    UserRole,
)
from app.modules.ingestion.models import (
    InvoiceFileRead,
    InvoiceRow,
    MessageRow,
    PaymentRow,
    PriceHistoryRow,
    PriceRow,
    PurchaseOrderRow,
    ResolutionRuleProjection,
    RowStatus,
    SaleRow,
    SupplierRow,
)
from app.modules.messaging.models import (
    MessageKind,
    MessageState,
    SupplierMessage,
    SupplierProjection,
)
from app.modules.notifications.models import (
    AlertKind,
    NotificationRecipient,
    NotificationRoute,
    NotificationSetting,
)
from app.modules.operations.models import AuditEntry, JobRun, JobStatus, Parameter
from app.modules.portal.models import PortalDocument
from app.modules.purchases.models import (
    DueDate,
    DueDateChange,
    DueDateOrigin,
    Invoice,
    InvoiceDocument,
    InvoiceReviewState,
    OrderReviewState,
    Payment,
    PaymentOrigin,
    PaymentState,
    PurchaseCorrection,
    PurchaseOrder,
    PurchaseSetting,
    Receipt,
    ReceiptIncident,
    Supplier,
    SupplierAlias,
    SupplierAliasSource,
)
from app.modules.sales.models import Sale, SalesProduct, SalesSetting, SaleState
from app.modules.triage.models import CaseStatus, ExceptionCase, ResolutionRule

__all__: list[str] = [
    "AccessEvent",
    "AccessEventKind",
    "AccessSetting",
    "AlertKind",
    "AliasSource",
    "AuditEntry",
    "CaseStatus",
    "CatalogSetting",
    "Category",
    "CategoryAlias",
    "Correction",
    "CredentialToken",
    "DueDate",
    "DueDateChange",
    "DueDateOrigin",
    "ExceptionCase",
    "Invoice",
    "InvoiceDocument",
    "InvoiceFileRead",
    "InvoiceReviewState",
    "InvoiceRow",
    "JobRun",
    "JobStatus",
    "MessageKind",
    "MessageRow",
    "MessageState",
    "NotificationRecipient",
    "NotificationRoute",
    "NotificationSetting",
    "OrderReviewState",
    "Parameter",
    "Payment",
    "PaymentOrigin",
    "PaymentRow",
    "PaymentState",
    "PortalDocument",
    "PriceHistoryRow",
    "PricePoint",
    "PriceRow",
    "PriceSource",
    "Product",
    "ProductPrice",
    "ProductStatus",
    "PurchaseCorrection",
    "PurchaseOrder",
    "PurchaseOrderRow",
    "PurchaseSetting",
    "Receipt",
    "ReceiptIncident",
    "ResolutionRule",
    "ResolutionRuleProjection",
    "RowStatus",
    "Sale",
    "SaleRow",
    "SaleState",
    "SalesProduct",
    "SalesSetting",
    "Session",
    "SessionRevocation",
    "StockPoint",
    "Supplier",
    "SupplierAlias",
    "SupplierAliasSource",
    "SupplierMessage",
    "SupplierProjection",
    "SupplierRow",
    "TokenPurpose",
    "User",
    "UserPassword",
    "UserRole",
]
