"""Browser automation over SIGProv.

The portal is not ours, has no API and is never written to (Artículo I). It also
exposes internal JSON endpoints that this module deliberately does **not** use:
they are a contract nobody promised us. Everything here reads the rendered
screen with Playwright, like a person would.

Two facts about the portal drive the shape of this file, both surveyed against
the live site on 2026-08-29:

* **The download link is generated by JavaScript when the button is clicked, and
  expires in 45 seconds.** So the link is never produced to be consumed later:
  the click and the download happen inside the same browser context, in one go.
* **The account is shared with the client's own staff.** Nothing here writes,
  nothing retries in a burst, and every visit closes its browser.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from types import TracebackType
from typing import Protocol, Self

from playwright.async_api import Browser, Page, Playwright, async_playwright
from playwright.async_api import Error as PlaywrightError

from app.config import settings
from app.logging import get_logger
from app.shared.errors import ExtractionError

logger = get_logger(__name__)

XLSX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
HTML_CONTENT_TYPE = "text/html; charset=utf-8"

PRICES_PATH = "/precios"
LOGIN_PATH = "/login"

DOWNLOAD_BUTTON = re.compile("Descargar planilla", re.IGNORECASE)
HISTORY_LINK = re.compile("Ver historial", re.IGNORECASE)

# What the caller is told when the portal cannot be read. The underlying
# Playwright error is logged, never propagated: its message can carry the URL
# the browser was on, and a login URL carries the account (Artículo VII).
UNREADABLE = "The portal could not be read"


@dataclass(frozen=True, slots=True)
class DownloadedDocument:
    """What came back from the portal, before anybody interprets it."""

    content: bytes
    content_type: str
    filename: str


class PortalReader(Protocol):
    """What the service needs from a portal client.

    A protocol, so the suite can run with the portal switched off (`TEST-03`):
    the tests pass a reader that answers from the fixtures in
    `tests/fixtures/portal/`, and no browser is ever started.
    """

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def download_price_list(self) -> DownloadedDocument: ...

    async def fetch_product_history(self, product_code: str) -> DownloadedDocument: ...


class PortalClient:
    """Logs into SIGProv and reads a section of it.

    Used as an async context manager, so the browser always closes:

        async with PortalClient() as portal:
            document = await portal.download_price_list()
    """

    def __init__(self) -> None:
        self._playwright: Playwright | None = None
        self._browser: Browser | None = None
        self._page: Page | None = None

    # --- Lifecycle -------------------------------------------------------

    async def __aenter__(self) -> Self:
        """Start a browser and log in."""
        try:
            self._playwright = await async_playwright().start()
            self._browser = await self._playwright.chromium.launch(
                headless=settings.PORTAL_HEADLESS
            )
            page = await self._browser.new_page(accept_downloads=True)
            page.set_default_timeout(settings.PORTAL_NAVIGATION_TIMEOUT_MS)
            self._page = page
            await self._login(page)
        except PlaywrightError as error:
            await self.__aexit__(type(error), error, error.__traceback__)
            raise self._unreadable("login", error) from None
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close the browser, whatever happened."""
        if self._browser is not None:
            await self._browser.close()
            self._browser = None
        if self._playwright is not None:
            await self._playwright.stop()
            self._playwright = None
        self._page = None

    # --- Sections --------------------------------------------------------

    async def download_price_list(self) -> DownloadedDocument:
        """Download the file of the day from the prices section.

        The click that generates the link and the download that consumes it
        happen here, together: the link expires in 45 seconds, so there is no
        step in between where it could be stored, queued or retried.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(PRICES_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            async with page.expect_download(
                timeout=settings.PORTAL_DOWNLOAD_TTL_SECONDS * 1000
            ) as pending:
                await page.get_by_role("button", name=DOWNLOAD_BUTTON).click()
            download = await pending.value
            path = await download.path()
            if path is None:  # pragma: no cover - Playwright kept no file
                raise ExtractionError(UNREADABLE, details={"section": "prices"})
            content = Path(path).read_bytes()
        except PlaywrightError as error:
            raise self._unreadable("prices", error) from None

        logger.info("Price list downloaded", extra={"bytes": len(content)})
        return DownloadedDocument(
            content=content,
            content_type=XLSX_CONTENT_TYPE,
            filename=download.suggested_filename,
        )

    async def fetch_product_history(self, product_code: str) -> DownloadedDocument:
        """Open the history screen of one product and return the rendered page.

        The screen is reached the way a person reaches it — from the row of the
        prices table — because the portal's product path (`/precios/p12`) is its
        own identifier and has nothing to do with the supplier's code.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(PRICES_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            row = page.locator("table.datos tbody tr").filter(has_text=product_code).first
            if await row.count() == 0:
                raise ExtractionError(
                    "The product is not listed in the prices section",
                    details={"product_code": product_code},
                )
            await row.get_by_role("link", name=HISTORY_LINK).click()
            await page.wait_for_selector("table.datos tbody tr")
            content = (await page.content()).encode("utf-8")
        except PlaywrightError as error:
            raise self._unreadable("price-history", error) from None

        logger.info("Product history read", extra={"product_code": product_code})
        return DownloadedDocument(
            content=content,
            content_type=HTML_CONTENT_TYPE,
            filename=f"{product_code}.html",
        )

    # --- Internals -------------------------------------------------------

    async def _login(self, page: Page) -> None:
        """Sign in with the credentials that live only in the environment."""
        await page.goto(self._url(LOGIN_PATH), wait_until="domcontentloaded")
        await page.fill("#usuario", settings.PORTAL_USER)
        await page.fill("#clave", settings.PORTAL_PASSWORD)
        await page.click("button[type=submit]")
        await page.wait_for_url(re.compile(r"/(menu|precios)"))
        logger.info("Signed into the portal")

    def _require_page(self) -> Page:
        """Return the page, or say plainly that the client was not opened."""
        if self._page is None:  # pragma: no cover - misuse, not a portal failure
            raise ExtractionError("The portal client is not open")
        return self._page

    @staticmethod
    def _url(path: str) -> str:
        return f"{settings.PORTAL_BASE_URL.rstrip('/')}{path}"

    @staticmethod
    def _unreadable(section: str, error: PlaywrightError) -> ExtractionError:
        """Wrap a browser failure without letting it carry credentials out.

        Playwright's messages quote the URL and the selector it was working on,
        and this module is the one place where the portal user and password are
        in scope. So the technical detail is logged here and the exception that
        leaves carries only the section.
        """
        logger.exception("Portal navigation failed", extra={"section": section})
        return ExtractionError(UNREADABLE, details={"section": section})
