"""Browser automation over SIGProv.

The portal is not ours, has no API and is never written to (Artículo I). It also
exposes internal JSON endpoints that this module deliberately does **not** use:
they are a contract nobody promised us. Everything here reads the rendered
screen with Playwright, like a person would.

Two facts about the portal drive the shape of this file, both surveyed against
the live site on 2026-08-29:

* **The download link is generated by JavaScript when the button is clicked, and
  expires in 45 seconds.** So the link is never produced to be consumed later:
  the click and the download happen inside the same browser context, in one go.
* **The account is shared with the client's own staff.** Nothing here writes,
  nothing retries in a burst, and every visit closes its browser.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from types import TracebackType
from typing import Protocol, Self

from playwright.async_api import Browser, Page, Playwright, async_playwright
from playwright.async_api import Error as PlaywrightError

from app.config import settings
from app.logging import get_logger
from app.shared.errors import ExtractionError

logger = get_logger(__name__)

XLSX_CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
HTML_CONTENT_TYPE = "text/html; charset=utf-8"

PRICES_PATH = "/precios"
LOGIN_PATH = "/login"
# The sections 004, 007 and 009 read. There is no `/proveedores`: the register
# of suppliers is `/estado-cuenta`, which the portal itself describes as the
# current account "agrupada por proveedor real", and that is what makes those
# eight legal names the canonical register.
INVOICES_PATH = "/facturas"
SUPPLIER_LEDGER_PATH = "/estado-cuenta"
PURCHASE_ORDERS_PATH = "/ordenes-compra"
# The inbox is at `/mensajes-internos`, and it used to say `/mensajes` here.
# That path answers 404: the nightly read failed every single time, and nothing
# said so louder than a job that ended badly. Verified against the live portal
# on 2026-08-31 — the menu links it as «Mensajes Internos».
MESSAGES_PATH = "/mensajes-internos"
SALES_PATH = "/ventas"

DOWNLOAD_BUTTON = re.compile("Descargar planilla", re.IGNORECASE)
HISTORY_LINK = re.compile("Ver historial", re.IGNORECASE)
INVOICE_BUTTON = re.compile("Descargar factura", re.IGNORECASE)
LEDGER_DETAIL_BUTTON = re.compile("Ver detalle", re.IGNORECASE)

PDF_CONTENT_TYPE = "application/pdf"

# What the caller is told when the portal cannot be read. The underlying
# Playwright error is logged, never propagated: its message can carry the URL
# the browser was on, and a login URL carries the account (Artículo VII).
UNREADABLE = "The portal could not be read"

# How long the register's table is given to redraw after a row is expanded. The
# detail is rendered by the portal's own script, and there is no request to wait
# on: `wait_for_selector` would return immediately on the row that is already
# open.
EXPAND_SETTLE_MS = 200


def _content_type_of(filename: str) -> str:
    """What kind of document the portal handed over, by its own file name.

    The three formats are the ones the invoices table declares — a PDF with a
    text layer, a scanned PDF, and a spreadsheet. Anything else keeps a generic
    type and reaches the readers all the same: whichever manages to read it
    wins, and if none does the invoice goes to a person with the file attached.
    """
    lowered = filename.lower()
    if lowered.endswith(".pdf"):
        return PDF_CONTENT_TYPE
    if lowered.endswith((".xlsx", ".xlsm")):
        return XLSX_CONTENT_TYPE
    return "application/octet-stream"


@dataclass(frozen=True, slots=True)
class DownloadedDocument:
    """What came back from the portal, before anybody interprets it."""

    content: bytes
    content_type: str
    filename: str


class PortalReader(Protocol):
    """What the service needs from a portal client.

    A protocol, so the suite can run with the portal switched off (`TEST-03`):
    the tests pass a reader that answers from the fixtures in
    `tests/fixtures/portal/`, and no browser is ever started.
    """

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def download_price_list(self) -> DownloadedDocument: ...

    async def fetch_product_history(self, product_code: str) -> DownloadedDocument: ...

    async def fetch_invoices(self) -> DownloadedDocument: ...

    async def download_invoice_file(self, invoice_number: str) -> DownloadedDocument: ...

    async def fetch_supplier_ledger(self) -> DownloadedDocument: ...

    async def fetch_purchase_orders(self) -> DownloadedDocument: ...

    async def fetch_messages(self) -> DownloadedDocument: ...

    async def fetch_sales(self) -> DownloadedDocument: ...


class PortalClient:
    """Logs into SIGProv and reads a section of it.

    Used as an async context manager, so the browser always closes:

        async with PortalClient() as portal:
            document = await portal.download_price_list()
    """

    def __init__(self) -> None:
        self._playwright: Playwright | None = None
        self._browser: Browser | None = None
        self._page: Page | None = None

    # --- Lifecycle -------------------------------------------------------

    async def __aenter__(self) -> Self:
        """Start a browser and log in."""
        try:
            self._playwright = await async_playwright().start()
            self._browser = await self._playwright.chromium.launch(
                headless=settings.PORTAL_HEADLESS
            )
            page = await self._browser.new_page(accept_downloads=True)
            page.set_default_timeout(settings.PORTAL_NAVIGATION_TIMEOUT_MS)
            self._page = page
            await self._login(page)
        except PlaywrightError as error:
            await self.__aexit__(type(error), error, error.__traceback__)
            raise self._unreadable("login", error) from None
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close the browser, whatever happened."""
        if self._browser is not None:
            await self._browser.close()
            self._browser = None
        if self._playwright is not None:
            await self._playwright.stop()
            self._playwright = None
        self._page = None

    # --- Sections --------------------------------------------------------

    async def download_price_list(self) -> DownloadedDocument:
        """Download the file of the day from the prices section.

        The click that generates the link and the download that consumes it
        happen here, together: the link expires in 45 seconds, so there is no
        step in between where it could be stored, queued or retried.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(PRICES_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            async with page.expect_download(
                timeout=settings.PORTAL_DOWNLOAD_TTL_SECONDS * 1000
            ) as pending:
                await page.get_by_role("button", name=DOWNLOAD_BUTTON).click()
            download = await pending.value
            path = await download.path()
            if path is None:  # pragma: no cover - Playwright kept no file
                raise ExtractionError(UNREADABLE, details={"section": "prices"})
            content = Path(path).read_bytes()
        except PlaywrightError as error:
            raise self._unreadable("prices", error) from None

        logger.info("Price list downloaded", extra={"bytes": len(content)})
        return DownloadedDocument(
            content=content,
            content_type=XLSX_CONTENT_TYPE,
            filename=download.suggested_filename,
        )

    async def fetch_product_history(self, product_code: str) -> DownloadedDocument:
        """Open the history screen of one product and return the rendered page.

        The screen is reached the way a person reaches it — from the row of the
        prices table — because the portal's product path (`/precios/p12`) is its
        own identifier and has nothing to do with the supplier's code.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(PRICES_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            row = page.locator("table.datos tbody tr").filter(has_text=product_code).first
            if await row.count() == 0:
                raise ExtractionError(
                    "The product is not listed in the prices section",
                    details={"product_code": product_code},
                )
            await row.get_by_role("link", name=HISTORY_LINK).click()
            await page.wait_for_selector("table.datos tbody tr")
            content = (await page.content()).encode("utf-8")
        except PlaywrightError as error:
            raise self._unreadable("price-history", error) from None

        logger.info("Product history read", extra={"product_code": product_code})
        return DownloadedDocument(
            content=content,
            content_type=HTML_CONTENT_TYPE,
            filename=f"{product_code}.html",
        )

    # --- The sections of 004, 007 and 009 --------------------------------

    async def fetch_invoices(self) -> DownloadedDocument:
        """Read the invoices screen, rendered. A hundred rows, no pagination."""
        return await self._rendered(INVOICES_PATH, "invoices", "facturas.html")

    async def fetch_purchase_orders(self) -> DownloadedDocument:
        """Read the purchase orders screen, rendered."""
        return await self._rendered(PURCHASE_ORDERS_PATH, "purchase-orders", "ordenes.html")

    async def fetch_messages(self) -> DownloadedDocument:
        """Read the inbox of the portal, rendered."""
        return await self._rendered(MESSAGES_PATH, "messages", "mensajes.html")

    async def fetch_sales(self) -> DownloadedDocument:
        """Read the sales screen, rendered."""
        return await self._rendered(SALES_PATH, "sales", "ventas.html")

    async def fetch_supplier_ledger(self) -> DownloadedDocument:
        """Read the register, expanding every supplier before taking the page.

        The detail opens with a click and the URL does not change, so there is
        no link to follow: it is eight clicks on the same screen, exactly what
        a person does. The page is captured **after** the last one, because the
        tax id, the email, the phone and the payment term exist nowhere else.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(SUPPLIER_LEDGER_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            buttons = page.get_by_role("button", name=LEDGER_DETAIL_BUTTON)
            for index in range(await buttons.count()):
                # Re-read the locator each time: expanding a row rewrites the
                # table, and a handle taken before that points at nothing.
                remaining = page.get_by_role("button", name=LEDGER_DETAIL_BUTTON)
                if await remaining.count() == 0:
                    break
                await remaining.first.click()
                await page.wait_for_timeout(EXPAND_SETTLE_MS)
                del index
            content = (await page.content()).encode("utf-8")
        except PlaywrightError as error:
            raise self._unreadable("supplier-ledger", error) from None

        logger.info("Supplier ledger read", extra={"bytes": len(content)})
        return DownloadedDocument(
            content=content, content_type=HTML_CONTENT_TYPE, filename="estado-cuenta.html"
        )

    async def download_invoice_file(self, invoice_number: str) -> DownloadedDocument:
        """Download the document of one invoice, from its row of the table.

        The click that generates the link and the download that consumes it
        happen together, like the price list: the link expires in 45 seconds.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(INVOICES_PATH), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            row = page.locator("table.datos tbody tr").filter(has_text=invoice_number).first
            if await row.count() == 0:
                raise ExtractionError(
                    "The invoice is not listed in the invoices section",
                    details={"invoice_number": invoice_number},
                )
            async with page.expect_download(
                timeout=settings.PORTAL_DOWNLOAD_TTL_SECONDS * 1000
            ) as pending:
                await row.get_by_role("button", name=INVOICE_BUTTON).click()
            download = await pending.value
            path = await download.path()
            if path is None:  # pragma: no cover - Playwright kept no file
                raise ExtractionError(UNREADABLE, details={"section": "invoice-file"})
            content = Path(path).read_bytes()
            filename = download.suggested_filename
        except PlaywrightError as error:
            raise self._unreadable("invoice-file", error) from None

        logger.info(
            "Invoice file downloaded",
            extra={"invoice_number": invoice_number, "bytes": len(content)},
        )
        return DownloadedDocument(
            content=content, content_type=_content_type_of(filename), filename=filename
        )

    # --- Internals -------------------------------------------------------

    async def _rendered(self, path: str, section: str, filename: str) -> DownloadedDocument:
        """Open a section and return its rendered table, or say it is unreadable.

        Four sections read the same way — go, wait for the table, take the DOM —
        so they share this instead of four copies of it. What differs between
        them is the parser, and the parser is not this module's business.
        """
        page = self._require_page()
        try:
            await page.goto(self._url(path), wait_until="domcontentloaded")
            await page.wait_for_selector("table.datos tbody tr")
            content = (await page.content()).encode("utf-8")
        except PlaywrightError as error:
            raise self._unreadable(section, error) from None

        logger.info("Section read", extra={"section": section, "bytes": len(content)})
        return DownloadedDocument(
            content=content, content_type=HTML_CONTENT_TYPE, filename=filename
        )

    async def _login(self, page: Page) -> None:
        """Sign in with the credentials that live only in the environment."""
        await page.goto(self._url(LOGIN_PATH), wait_until="domcontentloaded")
        await page.fill("#usuario", settings.PORTAL_USER)
        await page.fill("#clave", settings.PORTAL_PASSWORD)
        await page.click("button[type=submit]")
        await page.wait_for_url(re.compile(r"/(menu|precios)"))
        logger.info("Signed into the portal")

    def _require_page(self) -> Page:
        """Return the page, or say plainly that the client was not opened."""
        if self._page is None:  # pragma: no cover - misuse, not a portal failure
            raise ExtractionError("The portal client is not open")
        return self._page

    @staticmethod
    def _url(path: str) -> str:
        return f"{settings.PORTAL_BASE_URL.rstrip('/')}{path}"

    @staticmethod
    def _unreadable(section: str, error: PlaywrightError) -> ExtractionError:
        """Wrap a browser failure without letting it carry credentials out.

        Playwright's messages quote the URL and the selector it was working on,
        and this module is the one place where the portal user and password are
        in scope. So the technical detail is logged here and the exception that
        leaves carries only the section.
        """
        logger.exception("Portal navigation failed", extra={"section": section})
        return ExtractionError(UNREADABLE, details={"section": section})
