/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database health
         * @description Public and unauthenticated: Docker's healthcheck calls it before anyone logs in.
         *
         *     It answers 503 rather than 200 when a dependency is down, because an
         *     orchestrator restarts on the status code, not on the body.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for an access token
         * @description Public: anyone may attempt to log in.
         *
         *     A wrong email, a wrong password and a disabled account all fail the same
         *     way, so the endpoint cannot be used to find out which emails exist.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's own account
         * @description Any authenticated role, restricted to the caller's own account.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password reset link
         * @description Public, and always answers 200.
         *
         *     Reporting whether the address is registered would turn a recovery form into
         *     an account enumeration oracle, so the answer never varies.
         */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a reset token for a new password
         * @description Public: the single-use token is itself the credential.
         */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Any authenticated role, and only on the caller's own account.
         *
         *     The target user is taken from the token, never from the body, so this route
         *     cannot be pointed at somebody else's account.
         */
        post: operations["change_password_api_v1_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Every authenticated role: the team needs to know who its colleagues are.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * Create a user
         * @description Owner only: handing out accounts and roles is the owner's decision.
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a user
         * @description Every authenticated role.
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Deactivate a user
         * @description Owner only.
         *
         *     The account is deactivated, not deleted: the purchases, sales and messages
         *     it authored have to keep pointing at a real person.
         */
        delete: operations["deactivate_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Owner only: this route can change a role, so it changes what someone may do.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/operations/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent background runs
         * @description Every authenticated role.
         *
         *     Whoever handles purchasing needs to know whether last night's extraction
         *     ran, without having to ask the owner.
         */
        get: operations["list_jobs_api_v1_operations_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the business parameters
         * @description Owner only: these values decide how the platform behaves.
         */
        get: operations["list_parameters_api_v1_operations_parameters_get"];
        /**
         * Update the business parameters
         * @description Owner only.
         *
         *     The whole set is written in one transaction, so the platform never runs on
         *     half of the old rules and half of the new ones.
         */
        put: operations["update_parameters_api_v1_operations_parameters_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ComponentHealth
         * @description The state of one dependency.
         *
         *     `detail` is deliberately generic: `/health` is public, so it must not leak
         *     hostnames, drivers or credentials from the underlying exception. The real
         *     exception goes to the log.
         */
        ComponentHealth: {
            status: components["schemas"]["HealthState"];
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthRead
         * @description The answer of `/health`: the service plus every dependency it needs.
         */
        HealthRead: {
            status: components["schemas"]["HealthState"];
            /** Service */
            service: string;
            /** Environment */
            environment: string;
            database: components["schemas"]["ComponentHealth"];
        };
        /**
         * HealthState
         * @description How a component is answering right now.
         * @enum {string}
         */
        HealthState: "ok" | "down";
        /**
         * JobRunList
         * @description A page of runs.
         */
        JobRunList: {
            /** Items */
            items: components["schemas"]["JobRunRead"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /**
         * JobRunRead
         * @description A run as exposed by the API and to other modules.
         */
        JobRunRead: {
            /** Id */
            id: number;
            /** Task Name */
            task_name: string;
            status: components["schemas"]["JobStatus"];
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Attempts */
            attempts: number;
        };
        /**
         * JobStatus
         * @description The life of a run: queued, executing, and how it ended.
         * @enum {string}
         */
        JobStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
        /**
         * LoginRequest
         * @description Credentials submitted at login.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description A successful login.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /**
         * MessageResponse
         * @description A bare acknowledgement.
         *
         *     It carries no resource, which is why it lives here and not in `schemas.py`
         *     next to the identity contracts.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * ParameterRead
         * @description A business parameter as exposed by the API and to other modules.
         */
        ParameterRead: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Value */
            value: unknown;
            /** Description */
            description: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ParameterUpdateRequest
         * @description The body of `PUT /operations/parameters`.
         *
         *     The parameters screen saves every field at once, so the endpoint takes the
         *     whole set and applies it in one transaction: either all the changes land or
         *     none of them do.
         */
        ParameterUpdateRequest: {
            /** Items */
            items: components["schemas"]["ParameterWrite"][];
        };
        /**
         * ParameterWrite
         * @description A parameter to create or overwrite.
         *
         *     Leaving `description` unset keeps the stored one, so a caller that only
         *     changes the value does not have to resend the text next to the field.
         */
        ParameterWrite: {
            /** Key */
            key: string;
            /** Value */
            value: unknown;
            /** Description */
            description?: string | null;
        };
        /**
         * PasswordChangeRequest
         * @description Change your own password while authenticated.
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PasswordResetConfirm
         * @description Redeem a reset token for a new password.
         */
        PasswordResetConfirm: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PasswordResetRequest
         * @description Request a reset token for an email address.
         */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * UserCreate
         * @description Payload to create a user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** @default SALES */
            role: components["schemas"]["UserRole"];
            /** Password */
            password: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * UserList
         * @description A page of users.
         */
        UserList: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /**
         * UserRead
         * @description A user as exposed by the API and to other modules.
         */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Last Name */
            last_name: string | null;
            /** Phone */
            phone: string | null;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @description The three roles the business actually has.
         *
         *     Taken from the client's own words: the owner, whoever handles purchasing,
         *     and whoever handles sales. Authorisation is enforced per resource, not by
         *     hiding links in a menu.
         * @enum {string}
         */
        UserRole: "OWNER" | "PURCHASING" | "SALES";
        /**
         * UserUpdate
         * @description Payload to update a user. Every field is optional.
         */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                /** @description Rows to skip */
                skip?: number;
                /** @description Rows per page */
                limit?: number;
                /** @description Match name or email */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_operations_jobs_get: {
        parameters: {
            query?: {
                /** @description Rows to skip */
                skip?: number;
                /** @description Rows per page */
                limit?: number;
                /** @description Filter by task */
                task_name?: string | null;
                /** @description Filter by run status */
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parameters_api_v1_operations_parameters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterRead"][];
                };
            };
        };
    };
    update_parameters_api_v1_operations_parameters_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParameterUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
